apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  namespace: varun-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airflow-worker
  template:
    metadata:
      labels:
        app: airflow-worker
    spec:
      containers:
        - name: worker
          image: apache/airflow:2.7.3
          command: ["airflow", "celery"]
          args: ["worker"]
          envFrom:
            - configMapRef:
                name: airflow-config
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
      volumes:
        - name: dags
          emptyDir: {}
