apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: varun-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: scheduler
          image: apache/airflow:2.7.3
          command: ["scheduler"]
          envFrom:
            - configMapRef:
                name: airflow-config
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
      volumes:
        - name: dags
          emptyDir: {}
