apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-deck
  namespace: spinnaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spinnaker-deck
  template:
    metadata:
      labels:
        app: spinnaker-deck
    spec:
      containers:
        - name: spinnaker-deck
          image: nginx:alpine
          ports:
            - containerPort: 80
          env:
            - name: NGINX_HOST
              value: "0.0.0.0"
            - name: NGINX_PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: spinnaker-deck
  namespace: spinnaker
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: spinnaker-deck
