apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-deck
  namespace: spinnaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spinnaker-deck
  template:
    metadata:
      labels:
        app: spinnaker-deck
    spec:
      containers:
        - name: spinnaker-deck
          image: gcr.io/spinnaker-marketplace/deck:2.28.0
          ports:
            - containerPort: 9000
          env:
            - name: API_HOST
              value: "0.0.0.0"
            - name: API_PORT
              value: "8084"
---
apiVersion: v1
kind: Service
metadata:
  name: spinnaker-deck
  namespace: spinnaker
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: spinnaker-deck
